# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_cfdb9e6353bb2a72835f3377a24b515056151f2a

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client/src,controllers,models,routes,helpers,middlewares

sonar.language=js
sonar.inclusions=**/*.js
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.integration.test.js,**/*.unit.test.js,**/*.spec.ts,client/src/_site/**,controllers/__tests__/**/utils/**,controllers/__mocks__/**
sonar.javascript.lcov.reportPaths=coverage/sonar/lcov.info
